id: A24089869
title: f188A
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - ug
  - zh
  datatype: PlainText
  created_at: 2022-05-27 20:02:18.879276
  last_modified_at: 2022-05-27 20:02:18.879283
