id: A24089869
title: f717C
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - ug
  - zh
  datatype: PlainText
  created_at: 2022-05-27 20:02:19.420537
  last_modified_at: 2022-05-27 20:02:19.420546
