id: A24089869
title: fDAFC
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - ug
  - zh
  datatype: PlainText
  created_at: 2022-05-27 20:02:19.962798
  last_modified_at: 2022-05-27 20:02:19.962806
